on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.12
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing pie-chart and its dependencies
        run: raco pkg install --no-docs --auto --name pie-chart
      - name: Compiling pie-chart and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps pie-chart
      - name: Testing pie-chart
        run: raco test -x -p pie-chart
